export const BODY_TYPE_OPTIONS = [
  { value: 'Beefy', label: 'Beefy (肌肉型)' },
  { value: 'Buff', label: 'Buff (健壮)' },
  { value: 'Buxom', label: 'Buxom (丰满型)' },
  { value: 'Chubby', label: 'Chubby (微胖)' },
  { value: 'Curvy', label: 'Curvy (曲线型)' },
  { value: 'Fat', label: 'Fat (肥胖)' },
  { value: 'Fit', label: 'Fit (健身型)' },
  { value: 'Flyweight', label: 'Flyweight (轻量级)' },
  { value: 'Hefty', label: 'Hefty (壮实)' },
  { value: 'Lanky', label: 'Lanky (瘦长)' },
  { value: 'Large', label: 'Large (大只)' },
  { value: 'Midweight', label: 'Midweight (中量级)' },
  { value: 'Morbidly obese', label: 'Morbidly obese (病态肥胖)' },
  { value: 'Muscular', label: 'Muscular (肌肉)' },
  { value: 'Obese', label: 'Obese (肥胖)' },
  { value: 'Overweight', label: 'Overweight (超重)' },
  { value: 'Petite', label: 'Petite (娇小)' },
  { value: 'Plump', label: 'Plump (圆润)' },
  { value: 'Portly', label: 'Portly (福态)' },
  { value: 'Rotund', label: 'Rotund (圆胖)' },
  { value: 'Short', label: 'Short (矮小)' },
  { value: 'Skinny', label: 'Skinny (皮包骨)' },
  { value: 'Slight', label: 'Slight (纤细)' },
  { value: 'Slim', label: 'Slim (苗条)' },
  { value: 'Small', label: 'Small (小只)' },
  { value: 'Stocky', label: 'Stocky (矮壮)' },
  { value: 'Stout', label: 'Stout (敦实)' },
  { value: 'Tall', label: 'Tall (高大)' },
  { value: 'Thick', label: 'Thick (厚实)' },
  { value: 'Tiny', label: 'Tiny (小巧)' },
  { value: 'Underweight', label: 'Underweight (体重不足)' },
  { value: 'Voluptuous', label: 'Voluptuous (性感丰满)' },
  { value: 'Well-built', label: 'Well-built (体格健壮)' },
  { value: 'Well-endowed', label: 'Well-endowed (身材优越)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const FACIAL_EXPRESSION_OPTIONS = [
  { value: 'Amused', label: 'Amused (愉悦)' },
  { value: 'Angry', label: 'Angry (愤怒)' },
  { value: 'Anxious', label: 'Anxious (焦虑)' },
  { value: 'Bored', label: 'Bored (无聊)' },
  { value: 'Calm', label: 'Calm (平静)' },
  { value: 'Cautious', label: 'Cautious (谨慎)' },
  { value: 'Confused', label: 'Confused (困惑)' },
  { value: 'Contemptuous', label: 'Contemptuous (轻蔑)' },
  { value: 'Content', label: 'Content (满足)' },
  { value: 'Curious', label: 'Curious (好奇)' },
  { value: 'Disappointed', label: 'Disappointed (失望)' },
  { value: 'Disgusted', label: 'Disgusted (厌恶)' },
  { value: 'Envious', label: 'Envious (嫉妒)' },
  { value: 'Excited', label: 'Excited (兴奋)' },
  { value: 'Fearful', label: 'Fearful (恐惧)' },
  { value: 'Happy', label: 'Happy (开心)' },
  { value: 'In love', label: 'In love (恋爱)' },
  { value: 'Nervous', label: 'Nervous (紧张)' },
  { value: 'Peaceful', label: 'Peaceful (平和)' },
  { value: 'Pensive', label: 'Pensive (沉思)' },
  { value: 'Prideful', label: 'Prideful (骄傲)' },
  { value: 'Proud', label: 'Proud (自豪)' },
  { value: 'Relieved', label: 'Relieved (释然)' },
  { value: 'Sad', label: 'Sad (悲伤)' },
  { value: 'Sarcastic', label: 'Sarcastic (讽刺)' },
  { value: 'Serene', label: 'Serene (安详)' },
  { value: 'Serious', label: 'Serious (严肃)' },
  { value: 'Shy', label: 'Shy (害羞)' },
  { value: 'Silly', label: 'Silly (傻气)' },
  { value: 'Smiling', label: 'Smiling (微笑)' },
  { value: 'Surprised', label: 'Surprised (惊讶)' },
  { value: 'Surprised and Amused', label: 'Surprised and Amused (惊喜)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const HAIR_COLOR_OPTIONS = [
  { value: 'Auburn', label: 'Auburn (红褐色)' },
  { value: 'Black', label: 'Black (黑色)' },
  { value: 'Blonde', label: 'Blonde (金色)' },
  { value: 'Burgundy', label: 'Burgundy (酒红色)' },
  { value: 'Caramel', label: 'Caramel (焦糖色)' },
  { value: 'Chestnut', label: 'Chestnut (栗色)' },
  { value: 'Chocolate', label: 'Chocolate (巧克力色)' },
  { value: 'Copper', label: 'Copper (铜色)' },
  { value: 'Dirty', label: 'Dirty (脏金色)' },
  { value: 'Gray', label: 'Gray (灰色)' },
  { value: 'Honey', label: 'Honey (蜂蜜色)' },
  { value: 'Jet Black', label: 'Jet Black (乌黑)' },
  { value: 'Mahogany', label: 'Mahogany (桃花心木色)' },
  { value: 'Multicolored', label: 'Multicolored (多彩)' },
  { value: 'Pastel', label: 'Pastel (粉彩)' },
  { value: 'Platinum', label: 'Platinum (铂金)' },
  { value: 'Red', label: 'Red (红色)' },
  { value: 'Salt and pepper', label: 'Salt and pepper (花白)' },
  { value: 'Silver', label: 'Silver (银色)' },
  { value: 'Strawberry', label: 'Strawberry (草莓金)' },
  { value: 'White', label: 'White (白色)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const HAIR_LENGTH_OPTIONS = [
  { value: 'Long', label: 'Long (长发)' },
  { value: 'Medium', label: 'Medium (中发)' },
  { value: 'Short', label: 'Short (短发)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const SHOT_OPTIONS = [
  { value: 'Close-up', label: 'Close-up (特写)' },
  { value: 'Face', label: 'Face (脸部)' },
  { value: 'Full body', label: 'Full body (全身)' },
  { value: 'Full-length portrait', label: 'Full-length portrait (全身肖像)' },
  { value: 'Half-length portrait', label: 'Half-length portrait (半身肖像)' },
  { value: 'Head and shoulders portrait', label: 'Head and shoulders portrait (头像)' },
  { value: 'Head portrait', label: 'Head portrait (头部肖像)' },
  { value: 'Portrait', label: 'Portrait (肖像)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const CLOTHES_OPTIONS = [
  { value: 'Sheer Dress', label: 'Sheer Dress (透视裙)' },
  { value: 'Mesh Dress', label: 'Mesh Dress (网眼裙)' },
  { value: 'Slip Dress', label: 'Slip Dress (吊带裙)' },
  { value: 'Off-shoulder Dress', label: 'Off-shoulder Dress (露肩裙)' },
  { value: 'Bodycon Dress', label: 'Bodycon Dress (紧身裙)' },
  { value: 'Mini Dress', label: 'Mini Dress (超短裙)' },
  { value: 'Micro Dress', label: 'Micro Dress (迷你裙)' },
  { value: 'Cocktail Dress', label: 'Cocktail Dress (鸡尾酒裙)' },
  { value: 'Evening Gown', label: 'Evening Gown (晚礼服)' },
  { value: 'Boho Chic Dress', label: 'Boho Chic Dress (波西米亚风)' },
  { value: 'Lace Dress', label: 'Lace Dress (蕾丝裙)' },
  { value: 'Leather Dress', label: 'Leather Dress (皮裙)' },
  { value: 'Latex Dress', label: 'Latex Dress (乳胶裙)' },
  { value: 'Vinyl Dress', label: 'Vinyl Dress (乙烯基裙)' },
  { value: 'Corset Dress', label: 'Corset Dress (塑身裙)' },
  { value: 'Bustier Dress', label: 'Bustier Dress (紧身胸衣裙)' },
  { value: 'Cutout Dress', label: 'Cutout Dress (镂空裙)' },
  { value: 'See-through Dress', label: 'See-through Dress (透视礼服)' },
  { value: 'Backless Dress', label: 'Backless Dress (露背裙)' },
  { value: 'Low-rise Dress', label: 'Low-rise Dress (低腰裙)' },
  { value: 'Wet Look Dress', label: 'Wet Look Dress (湿感裙)' },
  { value: 'Fishnet Dress', label: 'Fishnet Dress (渔网裙)' },
  { value: 'Tulle Gown', label: 'Tulle Gown (薄纱礼服)' },
  { value: 'Satin Gown', label: 'Satin Gown (缎面礼服)' },
  { value: 'Silk Robe', label: 'Silk Robe (丝绸浴袍)' },
  { value: 'Kimono', label: 'Kimono (和服)' },
  { value: 'Maid Outfit', label: 'Maid Outfit (女仆装)' },
  { value: 'School Uniform', label: 'School Uniform (校服)' },
  { value: 'Nurse Uniform', label: 'Nurse Uniform (护士装)' },
  { value: 'Bunny Suit', label: 'Bunny Suit (兔女郎装)' },
  { value: 'Bikini Top and Mini Skirt', label: 'Bikini Top and Mini Skirt (比基尼+迷你裙)' },
  { value: 'Top and Shorts', label: 'Top and Shorts (背心+短裤)' },
  { value: 'Crop Top and Skirt', label: 'Crop Top and Skirt (短上衣+短裙)' },
  { value: 'Bandeau Top', label: 'Bandeau Top (无肩带胸衣)' },
  { value: 'Tube Top', label: 'Tube Top (管状上衣)' },
  { value: 'String Bikini', label: 'String Bikini (细线比基尼)' },
  { value: 'Micro Bikini', label: 'Micro Bikini (微型比基尼)' },
  { value: 'Tied-up Shirt', label: 'Tied-up Shirt (撩起上衣)' },
  { value: 'One Piece Swimsuit', label: 'One Piece Swimsuit (连体泳衣)' },
  { value: 'Bikini', label: 'Bikini (比基尼)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const LIGHT_DIRECTION_OPTIONS = [
  { value: 'Light from bottom', label: 'Light from bottom (底部光)' },
  { value: 'Light from bottom-left', label: 'Light from bottom-left (左下光)' },
  { value: 'Light from bottom-right', label: 'Light from bottom-right (右下光)' },
  { value: 'Light from front', label: 'Light from front (正面光)' },
  { value: 'Light from left', label: 'Light from left (左侧光)' },
  { value: 'Light from rear', label: 'Light from rear (背面光)' },
  { value: 'Light from right', label: 'Light from right (右侧光)' },
  { value: 'Light from top', label: 'Light from top (顶部光)' },
  { value: 'Light from top-left', label: 'Light from top-left (左上光)' },
  { value: 'Light from top-right', label: 'Light from top-right (右上光)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const LIGHT_TYPE_OPTIONS = [
  { value: 'Abstract Light Patterns', label: 'Abstract Light Patterns (抽象光效)' },
  { value: 'Ambient Light', label: 'Ambient Light (环境光)' },
  { value: 'Backlight Light', label: 'Backlight Light (逆光)' },
  { value: 'Backlit Silhouette Light', label: 'Backlit Silhouette Light (逆光剪影)' },
  { value: 'Bloom Light', label: 'Bloom Light (辉光)' },
  { value: 'Blue Hour Light', label: 'Blue Hour Light (蓝调光)' },
  { value: 'Broad Lighting Light', label: 'Broad Lighting Light (宽光)' },
  { value: 'Bulb Light', label: 'Bulb Light (灯泡光)' },
  { value: 'Buterfly Lighting Light', label: 'Butterfly Lighting Light (蝴蝶光)' },
  { value: 'Candlelight', label: 'Candlelight (烛光)' },
  { value: 'Caustics Light', label: 'Caustics Light (焦散光)' },
  { value: 'Cinematic Lighting Light', label: 'Cinematic Lighting Light (电影光效)' },
  { value: 'City Streetlights Light', label: 'City Streetlights Light (街灯光)' },
  { value: 'Cloudy Day Diffused Light', label: 'Cloudy Day Diffused Light (阴天散射光)' },
  { value: 'Corona Light', label: 'Corona Light (日冕光)' },
  { value: 'Crepuscular Rays Light', label: 'Crepuscular Rays Light (暮光)' },
  { value: 'Dappled Sunlight Light', label: 'Dappled Sunlight Light (斑驳阳光)' },
  { value: 'Dimly Lit Light', label: 'Dimly Lit Light (昏暗光)' },
  { value: 'Fill Light', label: 'Fill Light (补光)' },
  { value: 'Firelight', label: 'Firelight (火光)' },
  { value: 'Flash Photography Light', label: 'Flash Photography Light (闪光灯)' },
  { value: 'Fluorescent Lighting', label: 'Fluorescent Lighting (荧光灯)' },
  { value: 'Fog and Mist Light', label: 'Fog and Mist Light (雾灯光)' },
  { value: 'Glare Light', label: 'Glare Light (眩光)' },
  { value: 'Golden Hour Light', label: 'Golden Hour Light (黄金时段光)' },
  { value: 'Halos Light', label: 'Halos Light (光晕)' },
  { value: 'Harsh Sunlight Light', label: 'Harsh Sunlight Light (强烈日光)' },
  { value: 'Heat Haze Light', label: 'Heat Haze Light (热霾光)' },
  { value: 'High-Key Lighting Light', label: 'High-Key Lighting Light (高调光)' },
  { value: 'Incandescent Lighting', label: 'Incandescent Lighting (白炽灯)' },
  { value: 'Lantern Light', label: 'Lantern Light (灯笼光)' },
  { value: 'Lens Flare Light', label: 'Lens Flare Light (镜头光晕)' },
  { value: 'Lightning Light', label: 'Lightning Light (闪电光)' },
  { value: 'Loop Lighting Light', label: 'Loop Lighting Light (环形光)' },
  { value: 'Low-Key Lighting Light', label: 'Low-Key Lighting Light (低调光)' },
  { value: 'Mist Light', label: 'Mist Light (薄雾光)' },
  { value: 'Moonlight Light', label: 'Moonlight Light (月光)' },
  { value: 'Natural Light', label: 'Natural Light (自然光)' },
  { value: 'Neon Lights Light', label: 'Neon Lights Light (霓虹灯)' },
  { value: 'Overcast Sky Light', label: 'Overcast Sky Light (阴天光)' },
  { value: 'Rainbows Light', label: 'Rainbows Light (彩虹光)' },
  { value: 'Reflections Light', label: 'Reflections Light (反光)' },
  { value: 'Rembrandt Lighting Light', label: 'Rembrandt Lighting Light (伦勃朗光)' },
  { value: 'Rim Light', label: 'Rim Light (轮廓光)' },
  { value: 'Rim Lighting Light', label: 'Rim Lighting Light (边缘光)' },
  { value: 'Scattering Light', label: 'Scattering Light (散射光)' },
  { value: 'Shadows Light', label: 'Shadows Light (阴影光)' },
  { value: 'Side Light', label: 'Side Light (侧光)' },
  { value: 'Silhouette Light', label: 'Silhouette Light (剪影光)' },
  { value: 'Skylight Light', label: 'Skylight Light (天光)' },
  { value: 'Soft Ambient Light', label: 'Soft Ambient Light (柔和环境光)' },
  { value: 'Soft Light', label: 'Soft Light (柔光)' },
  { value: 'Softbox Lighting Light', label: 'Softbox Lighting Light (柔光箱光)' },
  { value: 'Speedlight Light', label: 'Speedlight Light (闪光灯光)' },
  { value: 'Split Lighting Light', label: 'Split Lighting Light (分割光)' },
  { value: 'Spot Light', label: 'Spot Light (聚光灯)' },
  { value: 'Spotlight Light', label: 'Spotlight Light (追光灯)' },
  { value: 'Stage Lighting Light', label: 'Stage Lighting Light (舞台灯光)' },
  { value: 'Strip Light', label: 'Strip Light (条形光)' },
  { value: 'Studio Lighting Light', label: 'Studio Lighting Light (影棚光)' },
  { value: 'Sunlight Light', label: 'Sunlight Light (日光)' },
  { value: 'Sunrise Warmth Light', label: 'Sunrise Warmth Light (日出暖光)' },
  { value: 'Sunset Glow Light', label: 'Sunset Glow Light (日落光)' },
  { value: 'Thuderstorms Light', label: 'Thunderstorms Light (雷暴光)' },
  { value: 'Top Light', label: 'Top Light (顶光)' },
  { value: 'Torchlight Light', label: 'Torchlight Light (手电光)' },
  { value: 'Tungsten Lighting Light', label: 'Tungsten Lighting Light (钨丝灯)' },
  { value: 'Twilight Hues Light', label: 'Twilight Hues Light (暮光色调)' },
  { value: 'Underlighting Light', label: 'Underlighting Light (底光)' },
  { value: 'Volumetric Lighting Light', label: 'Volumetric Lighting Light (体积光)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const MODEL_POSE_OPTIONS = [
  { value: 'Adjusting Clothing Pose', label: 'Adjusting Clothing Pose (整理衣物)' },
  { value: 'Against a Wall Pose', label: 'Against a Wall Pose (靠墙)' },
  { value: 'Ajusting Hair Pose', label: 'Ajusting Hair Pose (整理发型)' },
  { value: 'Arms Up Pose', label: 'Arms Up Pose (举手)' },
  { value: 'Artistic Dance Pose', label: 'Artistic Dance Pose (艺术舞蹈)' },
  { value: 'Back Arch Pose', label: 'Back Arch Pose (拱背)' },
  { value: 'Battle Pose', label: 'Battle Pose (战斗姿态)' },
  { value: 'Bending Pose', label: 'Bending Pose (弯腰)' },
  { value: 'Captivating Pose', label: 'Captivating Pose (迷人姿态)' },
  { value: 'Cartwheel Pose', label: 'Cartwheel Pose (侧手翻)' },
  { value: 'Casual Stroll Pose', label: 'Casual Stroll Pose (漫步)' },
  { value: 'Chassing Pose', label: 'Chassing Pose (追逐)' },
  { value: 'Classical Dance Pose', label: 'Classical Dance Pose (古典舞)' },
  { value: 'Close-Up Beauty Shot Pose', label: 'Close-Up Beauty Shot Pose (面部特写)' },
  { value: 'Confident Stance Pose', label: 'Confident Stance Pose (自信站姿)' },
  { value: 'Contrapposto Pose', label: 'Contrapposto Pose (对比姿势)' },
  { value: 'Crouching Pose', label: 'Crouching Pose (蹲姿)' },
  { value: 'Dancing Pose', label: 'Dancing Pose (舞蹈)' },
  { value: 'Dynamic Action Pose', label: 'Dynamic Action Pose (动感动作)' },
  { value: 'Dynamic Jump Pose', label: 'Dynamic Jump Pose (跳跃)' },
  { value: 'Dynamic Sitting Pose', label: 'Dynamic Sitting Pose (动态坐姿)' },
  { value: 'Eating Pose', label: 'Eating Pose (吃东西)' },
  { value: 'Expressive Female Pose', label: 'Expressive Female Pose (女性表现姿态)' },
  { value: 'Fashion Model Pose', label: 'Fashion Model Pose (时尚模特)' },
  { value: 'Feminine Pose', label: 'Feminine Pose (女性姿态)' },
  { value: 'Flipping Hair Pose', label: 'Flipping Hair Pose (甩发)' },
  { value: 'Gazing into the Distance Pose', label: 'Gazing into the Distance Pose (眺望)' },
  { value: 'Glamour Pose', label: 'Glamour Pose (魅力姿态)' },
  { value: 'Hand-on-Hip Pose', label: 'Hand-on-Hip Pose (叉腰)' },
  { value: 'Handstand Pose', label: 'Handstand Pose (倒立)' },
  { value: 'Headshot Pose', label: 'Headshot Pose (头像)' },
  { value: 'High Fashion Pose', label: 'High Fashion Pose (高级时尚)' },
  { value: 'Holding Bag Pose', label: 'Holding Bag Pose (拿包)' },
  { value: 'Holding Glass Pose', label: 'Holding Glass Pose (拿酒杯)' },
  { value: 'Holding Headset Pose', label: 'Holding Headset Pose (戴耳机)' },
  { value: 'Holding Ice Cream Pose', label: 'Holding Ice Cream Pose (拿冰淇淋)' },
  { value: 'Holding Microphone Pose', label: 'Holding Microphone Pose (拿麦克风)' },
  { value: 'Holding Pen Pose', label: 'Holding Pen Pose (拿笔)' },
  { value: 'Holding Phone Pose', label: 'Holding Phone Pose (拿手机)' },
  { value: 'Interacting with Props Pose', label: 'Interacting with Props Pose (与道具互动)' },
  { value: 'Jojo Pose', label: 'Jojo Pose (JOJO立)' },
  { value: 'Jumping Pose', label: 'Jumping Pose (跳跃)' },
  { value: 'Kneeling Pose', label: 'Kneeling Pose (跪姿)' },
  { value: 'Kung Fu Pose', label: 'Kung Fu Pose (功夫姿势)' },
  { value: 'Laughing Candidly Pose', label: 'Laughing Candidly Pose (开怀大笑)' },
  { value: 'Leaning Pose', label: 'Leaning Pose (倚靠)' },
  { value: 'Lifting Pose', label: 'Lifting Pose (举起)' },
  { value: 'Looking Back Over Shoulder Pose', label: 'Looking Back Over Shoulder Pose (回眸)' },
  { value: 'Lying Down Pose', label: 'Lying Down Pose (躺姿)' },
  { value: 'Magic Pose', label: 'Magic Pose (魔法姿势)' },
  { value: 'Masculine Pose', label: 'Masculine Pose (男性姿态)' },
  { value: 'Meditation Pose', label: 'Meditation Pose (冥想)' },
  { value: 'Movement Pose', label: 'Movement Pose (运动姿势)' },
  { value: 'Muscle Pose', label: 'Muscle Pose (肌肉姿势)' },
  { value: 'One Hand on Face Pose', label: 'One Hand on Face Pose (托腮)' },
  { value: 'One Leg Up Pose', label: 'One Leg Up Pose (单腿抬起)' },
  { value: 'Over-the-Shoulder Look Pose', label: 'Over-the-Shoulder Look Pose (肩后看)' },
  { value: 'Power Pose', label: 'Power Pose (力量姿势)' },
  { value: 'Reaching Pose', label: 'Reaching Pose (伸手)' },
  { value: 'Reading Book Pose', label: 'Reading Book Pose (读书)' },
  { value: 'Relaxing Pose', label: 'Relaxing Pose (放松姿势)' },
  { value: 'Relaxing Sitting Pose', label: 'Relaxing Sitting Pose (放松坐姿)' },
  { value: 'Riding Pose', label: 'Riding Pose (骑行姿势)' },
  { value: 'Royal Pose', label: 'Royal Pose (皇室姿势)' },
  { value: 'Running Pose', label: 'Running Pose (跑步)' },
  { value: 'S-curve Pose', label: 'S-curve Pose (S曲线)' },
  { value: 'S-shape Pose', label: 'S-shape Pose (S形)' },
  { value: 'Sexy Pose', label: 'Sexy Pose (性感姿势)' },
  { value: 'Sitting Cross-Legged Pose', label: 'Sitting Cross-Legged Pose (盘腿坐)' },
  { value: 'Sitting Pose', label: 'Sitting Pose (坐姿)' },
  { value: 'Skipping Pose', label: 'Skipping Pose (蹦跳)' },
  { value: 'Smoking Pose', label: 'Smoking Pose (吸烟姿势)' },
  { value: 'Standing Pose', label: 'Standing Pose (站姿)' },
  { value: 'Stretching Pose', label: 'Stretching Pose (伸展)' },
  { value: 'The Over-the-Shoulder Look Pose', label: 'The Over-the-Shoulder Look Pose (转身回眸)' },
  { value: 'Tilted Head Pose', label: 'Tilted Head Pose (歪头)' },
  { value: 'Touching Ear Pose', label: 'Touching Ear Pose (摸耳朵)' },
  { value: 'Touching Face Pose', label: 'Touching Face Pose (触摸脸部)' },
  { value: 'Touching Hair Pose', label: 'Touching Hair Pose (触摸头发)' },
  { value: 'Twirling Pose', label: 'Twirling Pose (旋转)' },
  { value: 'Upturned Eyes Shape', label: 'Upturned Eyes Shape (上挑眼)' },
  { value: 'Vogue Pose', label: 'Vogue Pose (Vogue姿势)' },
  { value: 'Walking Pose', label: 'Walking Pose (走路)' },
  { value: 'Watercolor Makeup Pose', label: 'Watercolor Makeup Pose (水彩妆容)' },
  { value: 'Waving Hand Pose', label: 'Waving Hand Pose (挥手)' },
  { value: 'Yoga Pose', label: 'Yoga Pose (瑜伽姿势)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const HAIR_STYLE_OPTIONS = [
  { value: 'A-line bob', label: 'A-line bob (A字波波头)' },
  { value: 'Afro', label: 'Afro (爆炸头)' },
  { value: 'Asymmetrical', label: 'Asymmetrical (不对称短发)' },
  { value: 'Balayage', label: 'Balayage (挑染)' },
  { value: 'Bald', label: 'Bald (光头)' },
  { value: 'Ballerina bun', label: 'Ballerina bun (芭蕾发髻)' },
  { value: 'Bangs', label: 'Bangs (刘海)' },
  { value: 'Beehive', label: 'Beehive (蜂窝头)' },
  { value: 'Beehivecut', label: 'Beehivecut (蜂窝剪裁)' },
  { value: 'Bleached spikes', label: 'Bleached spikes (漂白金刺猬头)' },
  { value: 'Blunt', label: 'Blunt (齐尾短发)' },
  { value: 'Blunt bob', label: 'Blunt bob (齐尾波波头)' },
  { value: 'Bob', label: 'Bob (波波头)' },
  { value: 'Bouffant', label: 'Bouffant (蓬松发髻)' },
  { value: 'Bowl', label: 'Bowl (锅盖头)' },
  { value: 'Box braids', label: 'Box braids (方块辫子)' },
  { value: 'Box fade', label: 'Box fade (方块渐变)' },
  { value: 'Braided', label: 'Braided (编织发)' },
  { value: 'Braided bob', label: 'Braided bob (编织波波头)' },
  { value: 'Braided pigtails', label: 'Braided pigtails (双马尾辫)' },
  { value: 'Brave shortcut with shaved sides', label: 'Brave shortcut with shaved sides (勇敢短发侧剃)' },
  { value: 'Bushy', label: 'Bushy (蓬松)' },
  { value: 'Buzz', label: 'Buzz (平头)' },
  { value: 'Caesar', label: 'Caesar (凯撒短发)' },
  { value: 'Chignon', label: 'Chignon (发髻)' },
  { value: 'Choppy', label: 'Choppy (凌乱短发)' },
  { value: 'Cloudy', label: 'Cloudy (云状卷发)' },
  { value: 'Cornrows', label: 'Cornrows (玉米辫)' },
  { value: 'Crew', label: 'Crew (平头)' },
  { value: 'Curly', label: 'Curly (卷发)' },
  { value: 'Curly Frizzy', label: 'Curly Frizzy (卷曲毛躁)' },
  { value: 'Curly bob', label: 'Curly bob (卷曲波波头)' },
  { value: 'Curtain bangs', label: 'Curtain bangs (窗帘刘海)' },
  { value: 'Deep side part', label: 'Deep side part (深侧分)' },
  { value: 'Double Bun', label: 'Double Bun (双丸子头)' },
  { value: 'Dreadlocks', label: 'Dreadlocks (脏辫)' },
  { value: 'Faded afro', label: 'Faded afro (渐变爆炸头)' },
  { value: 'Faux hawk', label: 'Faux hawk (仿莫西干)' },
  { value: 'Faux hawk short pixie', label: 'Faux hawk short pixie (短莫西干)' },
  { value: 'Feathered', label: 'Feathered (羽毛剪)' },
  { value: 'Female bald', label: 'Female bald (女性光头)' },
  { value: 'Fishtail braids', label: 'Fishtail braids (鱼尾辫)' },
  { value: 'Flat topcut', label: 'Flat topcut (平顶)' },
  { value: 'French bob', label: 'French bob (法式波波头)' },
  { value: 'French braids', label: 'French braids (法式辫子)' },
  { value: 'French twist', label: 'French twist (法式发髻)' },
  { value: 'Frohawk', label: 'Frohawk (毛刷莫西干)' },
  { value: 'Hair ringlets', label: 'Hair ringlets (环形卷发)' },
  { value: 'High ponytail', label: 'High ponytail (高马尾)' },
  { value: 'High skin fade', label: 'High skin fade (高渐变)' },
  { value: 'Italian bob', label: 'Italian bob (意式波波头)' },
  { value: 'Layered', label: 'Layered (层次感)' },
  { value: 'Lemonade braids', label: 'Lemonade braids (柠檬辫)' },
  { value: 'Long bob', label: 'Long bob (长波波头)' },
  { value: 'Long pixie', label: 'Long pixie (长精灵短发)' },
  { value: 'Long ponytail', label: 'Long ponytail (长马尾)' },
  { value: 'Long straight', label: 'Long straight (长直发)' },
  { value: 'Long with bangs', label: 'Long with bangs (长刘海)' },
  { value: 'Loose Curly Afro', label: 'Loose Curly Afro (松散卷曲爆炸头)' },
  { value: 'Marmaid waves', label: 'Marmaid waves (美人鱼卷)' },
  { value: 'Micro braids', label: 'Micro braids (细辫子)' },
  { value: 'Middle part ponytails', label: 'Middle part ponytails (中分双马尾)' },
  { value: 'Modern caesar', label: 'Modern caesar (现代凯撒)' },
  { value: 'Mohawk', label: 'Mohawk (莫西干)' },
  { value: 'Multicolored', label: 'Multicolored (多彩)' },
  { value: 'Pastel', label: 'Pastel (粉彩染)' },
  { value: 'Pigtails', label: 'Pigtails (双马尾)' },
  { value: 'Pixie', label: 'Pixie (精灵短发)' },
  { value: 'Platinum', label: 'Platinum (铂金染)' },
  { value: 'Pompadour', label: 'Pompadour (庞帕多)' },
  { value: 'Quiff', label: 'Quiff (飞机头)' },
  { value: 'Razor fade with curls', label: 'Razor fade with curls (剃刀渐变卷发)' },
  { value: 'Right side shaved', label: 'Right side shaved (右侧剃光)' },
  { value: 'Salt and pepper', label: 'Salt and pepper (花白)' },
  { value: 'Shag', label: 'Shag (蓬乱长发)' },
  { value: 'Short', label: 'Short (短发)' },
  { value: 'Short curly', label: 'Short curly (短卷发)' },
  { value: 'Short curly pixie', label: 'Short curly pixie (短卷精灵)' },
  { value: 'Short messy curls', label: 'Short messy curls (短乱卷发)' },
  { value: 'Shoulder Length with Bangs', label: 'Shoulder Length with Bangs (及肩刘海)' },
  { value: 'Shoulder length straight', label: 'Shoulder length straight (及肩直发)' },
  { value: 'Side Part Comb-Overstyle With High Fade', label: 'Side Part Comb-Overstyle With High Fade (侧分高渐变)' },
  { value: 'Side braid', label: 'Side braid (侧边辫子)' },
  { value: 'Side-swept bangs', label: 'Side-swept bangs (侧扫刘海)' },
  { value: 'Side-swept fringe', label: 'Side-swept fringe (侧扫碎发)' },
  { value: 'Sideswept pixie', label: 'Sideswept pixie (侧扫精灵)' },
  { value: 'Smooth lob', label: 'Smooth lob (柔顺长波波头)' },
  { value: 'Space buns', label: 'Space buns (太空球)' },
  { value: 'Spiky', label: 'Spiky (刺猬头)' },
  { value: 'Stacked Curls in Short Bob', label: 'Stacked Curls in Short Bob (短波波层叠卷)' },
  { value: 'Stacked bob', label: 'Stacked bob (层叠波波头)' },
  { value: 'Stitch braids', label: 'Stitch braids (缝线辫)' },
  { value: 'Strawberry', label: 'Strawberry (草莓金)' },
  { value: 'Strawberry blonde', label: 'Strawberry blonde (草莓金)' },
  { value: 'Sweeping pixie', label: 'Sweeping pixie (扫掠精灵)' },
  { value: 'Taper fade with waves', label: 'Taper fade with waves (渐变波浪)' },
  { value: 'Taperedcut with shaved side', label: 'Taperedcut with shaved side (锥形侧剃)' },
  { value: 'Textured', label: 'Textured (纹理感)' },
  { value: 'Textured brush back', label: 'Textured brush back (纹理背梳)' },
  { value: 'Tomboy', label: 'Tomboy (假小子)' },
  { value: 'Top Knot', label: 'Top Knot (丸子头)' },
  { value: 'Twin braids', label: 'Twin braids (双辫子)' },
  { value: 'Twintails', label: 'Twintails (双马尾)' },
  { value: 'Two dutch braids', label: 'Two dutch braids (双荷兰辫)' },
  { value: 'Undercut', label: 'Undercut (底部剃光)' },
  { value: 'Updo', label: 'Updo (盘发)' },
  { value: 'Very long wave', label: 'Very long wave (超长波浪)' },
  { value: 'Waterfall braids', label: 'Waterfall braids (瀑布辫)' },
  { value: 'Wavy', label: 'Wavy (波浪)' },
  { value: 'Wavy French Bob Vibes from 1920', label: 'Wavy French Bob Vibes from 1920 (1920风法式波波)' },
  { value: 'Wavy bob', label: 'Wavy bob (波浪波波头)' },
  { value: 'Wavy undercut', label: 'Wavy undercut (波浪底剃)' },
  { value: 'Wavy with curtain bangs', label: 'Wavy with curtain bangs (波浪窗帘刘海)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const FEMALE_LINGERIE_OPTIONS = [
  { value: 'Babydoll set in pastel pink with floral embroidery lingerie', label: 'Babydoll set in pastel pink with floral embroidery lingerie (粉色碎花睡裙套装)' },
  { value: 'Beaded Mesh Teddy lingerie', label: 'Beaded Mesh Teddy lingerie (珠饰网纱连体衣)' },
  { value: 'Black latex waist cincher with matching pasties lingerie', label: 'Black latex waist cincher with matching pasties lingerie (黑色乳胶束腰配乳贴)' },
  { value: 'Bridal lingerie set with pearls and lace lingerie', label: 'Bridal lingerie set with pearls and lace lingerie (珍珠蕾丝婚纱内衣套装)' },
  { value: 'Butterfly themed sheer bra and split skirt lingerie', label: 'Butterfly themed sheer bra and split skirt lingerie (蝴蝶主题透视胸罩和开叉裙)' },
  { value: 'Caged Lace Teddy lingerie', label: 'Caged Lace Teddy lingerie (镂空蕾丝连体衣)' },
  { value: 'Caged Underbust Corset lingerie', label: 'Caged Underbust Corset lingerie (镂空下胸塑身衣)' },
  { value: 'Classic black lace bralette with matching high-waisted panties lingerie', label: 'Classic black lace bralette with matching high-waisted panties lingerie (经典黑色蕾丝文胸配高腰内裤)' },
  { value: 'Cobalt blue sheer panel chemise lingerie', label: 'Cobalt blue sheer panel chemise lingerie (钴蓝色透视衬裙)' },
  { value: 'Contrast lace paneling teddy in black and white lingerie', label: 'Contrast lace paneling teddy in black and white lingerie (黑白对比蕾丝连体衣)' },
  { value: 'Convertible Strapless Bra lingerie', label: 'Convertible Strapless Bra lingerie (可转换无肩带文胸)' },
  { value: 'Corded Lace Teddy lingerie', label: 'Corded Lace Teddy lingerie (绳纹蕾丝连体衣)' },
  { value: 'Cotton Blend Wireless Bra lingerie', label: 'Cotton Blend Wireless Bra lingerie (棉混纺无线文胸)' },
  { value: 'Cotton Ribbed Bralette lingerie', label: 'Cotton Ribbed Bralette lingerie (棉质罗纹文胸)' },
  { value: 'Cotton Ruffle Bralette lingerie', label: 'Cotton Ruffle Bralette lingerie (棉质褶皱文胸)' },
  { value: 'Cotton Soft Cup Bra lingerie', label: 'Cotton Soft Cup Bra lingerie (棉质软杯文胸)' },
  { value: 'Crochet Halter Bralette lingerie', label: 'Crochet Halter Bralette lingerie (钩针吊带文胸)' },
  { value: 'Crochet Lace Bralette lingerie', label: 'Crochet Lace Bralette lingerie (钩针蕾丝文胸)' },
  { value: 'Crochet Lace Panty lingerie', label: 'Crochet Lace Panty lingerie (钩针蕾丝内裤)' },
  { value: 'Crochet Trim Bra lingerie', label: 'Crochet Trim Bra lingerie (钩针边饰文胸)' },
  { value: 'Crochet Trim Chemise lingerie', label: 'Crochet Trim Chemise lingerie (钩针边饰衬裙)' },
  { value: 'Crochet lace halter neck teddy lingerie', label: 'Crochet lace halter neck teddy lingerie (钩针蕾丝吊颈连体衣)' },
  { value: 'Cross-Back Bikini Top lingerie', label: 'Cross-Back Bikini Top lingerie (交叉背比基尼)' },
  { value: 'Cut-Out Back Teddy lingerie', label: 'Cut-Out Back Teddy lingerie (镂空背连体衣)' },
  { value: 'Cut-Out Detail Bra lingerie', label: 'Cut-Out Detail Bra lingerie (镂空细节文胸)' },
  { value: 'Cut-Out Lace Bodysuit lingerie', label: 'Cut-Out Lace Bodysuit lingerie (镂空蕾丝紧身衣)' },
  { value: 'Cut-Out Mesh Bodysuit lingerie', label: 'Cut-Out Mesh Bodysuit lingerie (镂空网纱紧身衣)' },
  { value: 'Cut-Out Sheer Teddy lingerie', label: 'Cut-Out Sheer Teddy lingerie (镂空透视连体衣)' },
  { value: 'Cut-out panels monokini-style bodysuit lingerie', label: 'Cut-out panels monokini-style bodysuit lingerie (镂空莫诺基尼紧身衣)' },
  { value: 'Cutout Lace Bralette lingerie', label: 'Cutout Lace Bralette lingerie (镂空蕾丝文胸)' },
  { value: 'Deep blue velvet bodysuit with a plunging neckline lingerie', label: 'Deep blue velvet bodysuit with a plunging neckline lingerie (深蓝色天鹅绒深V紧身衣)' },
  { value: 'Deep plunge lace-up back teddy in satin lingerie', label: 'Deep plunge lace-up back teddy in satin lingerie (缎面深V绑背连体衣)' },
  { value: 'Draped Satin Corset Top lingerie', label: 'Draped Satin Corset Top lingerie (缎面塑身胸罩)' },
  { value: 'Egyptian inspired gold bra and sheer draping skirt lingerie', label: 'Egyptian inspired gold bra and sheer draping skirt lingerie (埃及风金罩杯配透视裙)' },
  { value: 'Elegant longline bra and tap pant set in ivory lingerie', label: 'Elegant longline bra and tap pant set in ivory lingerie (象牙色优雅长款文胸和护垫裤套装)' },
  { value: 'Embellished Mesh Gown lingerie', label: 'Embellished Mesh Gown lingerie (装饰网纱礼服)' },
  { value: 'Embellished bustier with rhinestone detailing lingerie', label: 'Embellished bustier with rhinestone detailing lingerie (水钻装饰紧身胸衣)' },
  { value: 'Embroidered Cup Bustier lingerie', label: 'Embroidered Cup Bustier lingerie (刺绣杯罩)' },
  { value: 'Embroidered High Waist Brief lingerie', label: 'Embroidered High Waist Brief lingerie (刺绣高腰内裤)' },
  { value: 'Embroidered Lace Corset lingerie', label: 'Embroidered Lace Corset lingerie (刺绣蕾丝塑身衣)' },
  { value: 'Embroidered Longline Bra lingerie', label: 'Embroidered Longline Bra lingerie (刺绣长款文胸)' },
  { value: 'Embroidered Mesh Chemise lingerie', label: 'Embroidered Mesh Chemise lingerie (刺绣网纱衬裙)' },
  { value: 'Embroidered Mesh Panty lingerie', label: 'Embroidered Mesh Panty lingerie (刺绣网纱内裤)' },
  { value: 'Embroidered Mesh Teddy lingerie', label: 'Embroidered Mesh Teddy lingerie (刺绣网纱连体衣)' },
  { value: 'Embroidered Silk Bralette lingerie', label: 'Embroidered Silk Bralette lingerie (刺绣丝绸文胸)' },
  { value: 'Embroidered Strapless Bra lingerie', label: 'Embroidered Strapless Bra lingerie (刺绣无肩带文胸)' },
  { value: 'Embroidered Tulle Bodysuit lingerie', label: 'Embroidered Tulle Bodysuit lingerie (刺绣薄纱紧身衣)' },
  { value: 'Embroidered Velvet Teddy lingerie', label: 'Embroidered Velvet Teddy lingerie (刺绣天鹅绒连体衣)' },
  { value: 'Eyelash Lace Gown lingerie', label: 'Eyelash Lace Gown lingerie (睫毛蕾丝礼服)' },
  { value: 'Faux Fur Trim Robe lingerie', label: 'Faux Fur Trim Robe lingerie (人造毛边长袍)' },
  { value: 'Faux Leather Thong lingerie', label: 'Faux Leather Thong lingerie (人造皮革丁字裤)' },
  { value: 'Faux Suede Bodysuit lingerie', label: 'Faux Suede Bodysuit lingerie (仿麂皮紧身衣)' },
  { value: 'Faux leather plunge bodysuit with studs lingerie', label: 'Faux leather plunge bodysuit with studs lingerie (铆钉仿皮革深V紧身衣)' },
  { value: 'Feather Accented Babydoll lingerie', label: 'Feather Accented Babydoll lingerie (羽毛装饰睡裙)' },
  { value: 'Fishnet Floral Triangle Teddy lingerie', label: 'Fishnet Floral Triangle Teddy lingerie (渔网花卉三角连体衣)' },
  { value: 'Fishnet Halter Bodystocking lingerie', label: 'Fishnet Halter Bodystocking lingerie (渔网吊带连体袜)' },
  { value: 'Fishnet Strappy Teddy lingerie', label: 'Fishnet Strappy Teddy lingerie (渔网绑带连体衣)' },
  { value: 'Fishnet bodystocking with cutouts lingerie', label: 'Fishnet bodystocking with cutouts lingerie (镂空渔网连体袜)' },
  { value: 'Floral Applique Teddy lingerie', label: 'Floral Applique Teddy lingerie (花卉贴花连体衣)' },
  { value: 'Floral Embroidered Bodystocking lingerie', label: 'Floral Embroidered Bodystocking lingerie (花卉刺绣连体袜)' },
  { value: 'Floral Lace Corset lingerie', label: 'Floral Lace Corset lingerie (花卉蕾丝塑身衣)' },
  { value: 'Floral Lace G-String lingerie', label: 'Floral Lace G-String lingerie (花卉蕾丝G弦)' },
  { value: 'Floral Lace Slip lingerie', label: 'Floral Lace Slip lingerie (花卉蕾丝吊带裙)' },
  { value: 'Floral Print Balconette Bra lingerie', label: 'Floral Print Balconette Bra lingerie (花卉印花短杯文胸)' },
  { value: 'Floral Print Chemise lingerie', label: 'Floral Print Chemise lingerie (花卉印花衬裙)' },
  { value: 'Floral Trim Bra lingerie', label: 'Floral Trim Bra lingerie (花卉边饰文胸)' },
  { value: 'Floral lace kimono with a silk tie waist lingerie', label: 'Floral lace kimono with a silk tie waist lingerie (花卉蕾丝和服配丝绸腰带)' },
  { value: 'Fringe Detail Chemise lingerie', label: 'Fringe Detail Chemise lingerie (流苏细节衬裙)' },
  { value: 'Fringe Lace Teddy lingerie', label: 'Fringe Lace Teddy lingerie (流苏蕾丝连体衣)' },
  { value: 'Fringed silk bra top and high-waist panties lingerie', label: 'Fringed silk bra top and high-waist panties lingerie (丝绸罩杯配高腰内裤)' },
  { value: 'Front Closure Lace Bra lingerie', label: 'Front Closure Lace Bra lingerie (前扣蕾丝文胸)' },
  { value: 'Gauze Babydoll Dress lingerie', label: 'Gauze Babydoll Dress lingerie (纱布睡裙)' },
  { value: 'Glitter Mesh Teddy lingerie', label: 'Glitter Mesh Teddy lingerie (闪光网纱连体衣)' },
  { value: 'Glitter Trim Corset lingerie', label: 'Glitter Trim Corset lingerie (闪光边饰塑身衣)' },
  { value: 'Halter Plunge Crotchless Teddy lingerie', label: 'Halter Plunge Crotchless Teddy lingerie (吊带深V开裆连体衣)' },
  { value: 'High Impact Convertible Bra lingerie', label: 'High Impact Convertible Bra lingerie (高强度可转换文胸)' },
  { value: 'High Neck Lace Bralette lingerie', label: 'High Neck Lace Bralette lingerie (高领蕾丝文胸)' },
  { value: 'High Waist Satin Brief lingerie', label: 'High Waist Satin Brief lingerie (高腰缎面内裤)' },
  { value: 'High neck mesh bodice with lace panels lingerie', label: 'High neck mesh bodice with lace panels lingerie (高领网纱紧身胸衣配蕾丝板)' },
  { value: 'High-Leg Lace Brief lingerie', label: 'High-Leg Lace Brief lingerie (高腿蕾丝内裤)' },
  { value: 'High-Waist Shaping Thong lingerie', label: 'High-Waist Shaping Thong lingerie (高腰塑形丁字裤)' },
  { value: 'High-Waisted Lace Panty Set lingerie', label: 'High-Waisted Lace Panty Set lingerie (高腰蕾丝内裤套装)' },
  { value: 'High-gloss PVC catsuit with front zipper lingerie', label: 'High-gloss PVC catsuit with front zipper lingerie (高光PVC连体衣配前拉链)' },
  { value: 'Houndstooth Print Garter Belt lingerie', label: 'Houndstooth Print Garter Belt lingerie (千鸟格印花吊袜带)' },
  { value: 'Jacquard print underbust corset with lace-up back lingerie', label: 'Jacquard print underbust corset with lace-up back lingerie (提花塑身衣配绑背)' },
  { value: 'Jersey Knit Bikini Brief lingerie', label: 'Jersey Knit Bikini Brief lingerie (针织比基尼内裤)' },
  { value: 'Jersey Knit Thong lingerie', label: 'Jersey Knit Thong lingerie (针织丁字裤)' },
  { value: 'Jersey Lace-Up Chemise lingerie', label: 'Jersey Lace-Up Chemise lingerie (针织绑带衬裙)' },
  { value: 'Jersey Wrap Robe lingerie', label: 'Jersey Wrap Robe lingerie (针织裹身长袍)' },
  { value: 'Keyhole front halter bodysuit in shimmering fabric lingerie', label: 'Keyhole front halter bodysuit in shimmering fabric lingerie (闪光面料镂空前吊带紧身衣)' },
  { value: 'Knit Jersey Slip Dress lingerie', label: 'Knit Jersey Slip Dress lingerie (针织吊带裙)' },
  { value: 'Knit Lace Garter Belt lingerie', label: 'Knit Lace Garter Belt lingerie (针织蕾丝吊袜带)' },
  { value: 'Lace Bodice Nightgown lingerie', label: 'Lace Bodice Nightgown lingerie (蕾丝紧身胸衣睡袍)' },
  { value: 'Lace Cap Sleeve Teddy lingerie', label: 'Lace Cap Sleeve Teddy lingerie (蕾丝盖袖连体衣)' },
  { value: 'Lace Detail Slip Dress lingerie', label: 'Lace Detail Slip Dress lingerie (蕾丝细节吊带裙)' },
  { value: 'Lace Edged Thong lingerie', label: 'Lace Edged Thong lingerie (蕾丝边丁字裤)' },
  { value: 'Lace Embellished Bustier lingerie', label: 'Lace Embellished Bustier lingerie (蕾丝装饰紧身胸衣)' },
  { value: 'Lace Full Coverage Bra lingerie', label: 'Lace Full Coverage Bra lingerie (蕾丝全罩杯文胸)' },
  { value: 'Lace Halter Plunge Teddy lingerie', label: 'Lace Halter Plunge Teddy lingerie (蕾丝吊带深V连体衣)' },
  { value: 'Lace High-Neck Teddy lingerie', label: 'Lace High-Neck Teddy lingerie (蕾丝高领连体衣)' },
  { value: 'Lace Inset Slip lingerie', label: 'Lace Inset Slip lingerie (蕾丝嵌件吊带裙)' },
  { value: 'Lace Overlay Corset lingerie', label: 'Lace Overlay Corset lingerie (蕾丝覆盖塑身衣)' },
  { value: 'Lace Overlay Panty lingerie', label: 'Lace Overlay Panty lingerie (蕾丝覆盖内裤)' },
  { value: 'Lace Trim Cycling Shorts lingerie', label: 'Lace Trim Cycling Shorts lingerie (蕾丝边骑行短裤)' },
  { value: 'Lace Trim Maternity Bra lingerie', label: 'Lace Trim Maternity Bra lingerie (蕾丝边孕妇文胸)' },
  { value: 'Lace Trim Silk Bodysuit lingerie', label: 'Lace Trim Silk Bodysuit lingerie (蕾丝边丝绸紧身衣)' },
  { value: 'Lace Trimmed Bodysuit lingerie', label: 'Lace Trimmed Bodysuit lingerie (蕾丝边紧身衣)' },
  { value: 'Lace Trimmed Robe lingerie', label: 'Lace Trimmed Robe lingerie (蕾丝边长袍)' },
  { value: 'Lace Trimmed Silk Shorts lingerie', label: 'Lace Trimmed Silk Shorts lingerie (蕾丝边丝绸短裤)' },
  { value: 'Lace Wing Push-Up Bra lingerie', label: 'Lace Wing Push-Up Bra lingerie (蕾丝翼聚拢文胸)' },
  { value: 'Lace and Pearl Thong lingerie', label: 'Lace and Pearl Thong lingerie (蕾丝珍珠丁字裤)' },
  { value: 'Lace and Velvet Corset lingerie', label: 'Lace and Velvet Corset lingerie (蕾丝天鹅绒塑身衣)' },
  { value: 'Lace and leather mixed fabric bodysuit with zippers lingerie', label: 'Lace and leather mixed fabric bodysuit with zippers lingerie (蕾丝皮革混纺紧身衣配拉链)' },
  { value: 'Lace-Up Front Corset lingerie', label: 'Lace-Up Front Corset lingerie (前绑带塑身衣)' },
  { value: 'Lace-Up Leather Teddy lingerie', label: 'Lace-Up Leather Teddy lingerie (绑带皮革连体衣)' },
  { value: 'Lace-Up Satin Corset lingerie', label: 'Lace-Up Satin Corset lingerie (缎面绑带塑身衣)' },
  { value: 'Leather Buckle Corset lingerie', label: 'Leather Buckle Corset lingerie (皮革扣塑身衣)' },
  { value: 'Leather Halter Bodysuit lingerie', label: 'Leather Halter Bodysuit lingerie (皮革吊带紧身衣)' },
  { value: 'Leather Paneled Bralette lingerie', label: 'Leather Paneled Bralette lingerie (皮革嵌件文胸)' },
  { value: 'Leather and Lace Bustier lingerie', label: 'Leather and Lace Bustier lingerie (皮革蕾丝紧身胸衣)' },
  { value: 'Leather and Mesh Bodysuit lingerie', label: 'Leather and Mesh Bodysuit lingerie (皮革网纱紧身衣)' },
  { value: 'Leatherette Strapless Bra lingerie', label: 'Leatherette Strapless Bra lingerie (仿皮革无肩带文胸)' },
  { value: 'Leopard Print Bikini Brief lingerie', label: 'Leopard Print Bikini Brief lingerie (豹纹印花比基尼内裤)' },
  { value: 'Leopard print teddy with black lace details lingerie', label: 'Leopard print teddy with black lace details lingerie (豹纹连体衣配黑色蕾丝细节)' },
  { value: 'Lightly lined underwire cup teddy with floral print lingerie', label: 'Lightly lined underwire cup teddy with floral print lingerie (花卉印花钢圈杯连体衣)' },
  { value: 'Lurex Detail G-String lingerie', label: 'Lurex Detail G-String lingerie (金属丝G弦)' },
  { value: 'Luxurious marabou robe over a satin slip lingerie', label: 'Luxurious marabou robe over a satin slip lingerie (奢华羽毛长袍配缎面吊带裙)' },
  { value: 'Mesh Back Bikini Brief lingerie', label: 'Mesh Back Bikini Brief lingerie (网纱背比基尼内裤)' },
  { value: 'Mesh Cutout Bra lingerie', label: 'Mesh Cutout Bra lingerie (网纱镂空文胸)' },
  { value: 'Mesh Layered Teddy lingerie', label: 'Mesh Layered Teddy lingerie (网纱层叠连体衣)' },
  { value: 'Mesh Overlay Bralette lingerie', label: 'Mesh Overlay Bralette lingerie (网纱覆盖文胸)' },
  { value: 'Mesh Panel Corset lingerie', label: 'Mesh Panel Corset lingerie (网纱嵌件塑身衣)' },
  { value: 'Mesh Paneled Bodysuit lingerie', label: 'Mesh Paneled Bodysuit lingerie (网纱嵌件紧身衣)' },
  { value: 'Mesh Ruffle Chemise lingerie', label: 'Mesh Ruffle Chemise lingerie (网纱褶皱衬裙)' },
  { value: 'Mesh Trimmed Teddy lingerie', label: 'Mesh Trimmed Teddy lingerie (网纱边饰连体衣)' },
  { value: 'Metallic Detail Babydoll lingerie', label: 'Metallic Detail Babydoll lingerie (金属细节睡裙)' },
  { value: 'Metallic Lace Babydoll lingerie', label: 'Metallic Lace Babydoll lingerie (金属蕾丝睡裙)' },
  { value: 'Metallic Lace Teddy lingerie', label: 'Metallic Lace Teddy lingerie (金属蕾丝连体衣)' },
  { value: 'Metallic Trim Teddy lingerie', label: 'Metallic Trim Teddy lingerie (金属边饰连体衣)' },
  { value: 'Metallic gold bikini top and micro mini skirt lingerie', label: 'Metallic gold bikini top and micro mini skirt lingerie (金色比基尼配超迷你裙)' },
  { value: 'Microfiber Boxer Brief lingerie', label: 'Microfiber Boxer Brief lingerie (超细纤维拳击手内裤)' },
  { value: 'Mixed mesh and lace panel long sleeve bodysuit lingerie', label: 'Mixed mesh and lace panel long sleeve bodysuit lingerie (网纱蕾丝混纺长袖紧身衣)' },
  { value: 'Modal Lounge Bodysuit lingerie', label: 'Modal Lounge Bodysuit lingerie (莫代尔家居紧身衣)' },
  { value: 'Multi-strap halter bra and g-string with chains lingerie', label: 'Multi-strap halter bra and g-string with chains lingerie (多带吊带文胸和链条G弦)' },
  { value: 'Neon Lace Babydoll lingerie', label: 'Neon Lace Babydoll lingerie (霓虹蕾丝睡裙)' },
  { value: 'Neon Trim Bikini Brief lingerie', label: 'Neon Trim Bikini Brief lingerie (霓虹边比基尼内裤)' },
  { value: 'Neon mesh cutout bodysuit with glowing effects under black light lingerie', label: 'Neon mesh cutout bodysuit with glowing effects under black light lingerie (紫外光下发光网纱镂空紧身衣)' },
  { value: 'Neon pink triangle bralette and boyshorts lingerie', label: 'Neon pink triangle bralette and boyshorts lingerie (霓虹粉三角文胸和平角裤)' },
  { value: 'Neoprene Cutout Bralette lingerie', label: 'Neoprene Cutout Bralette lingerie (氯丁橡胶镂空文胸)' },
  { value: 'Neoprene Strappy Bra lingerie', label: 'Neoprene Strappy Bra lingerie (氯丁橡胶绑带文胸)' },
  { value: 'Neoprene Zip Bra lingerie', label: 'Neoprene Zip Bra lingerie (氯丁橡胶拉链文胸)' },
  { value: 'Peek-a-boo cup bra and crotchless panty lingerie', label: 'Peek-a-boo cup bra and crotchless panty lingerie (透视杯文胸和开裆内裤)' },
  { value: 'Peekaboo Cup Teddy lingerie', label: 'Peekaboo Cup Teddy lingerie (透视杯连体衣)' },
  { value: 'Pin-up style polka dot bra and high-waist panties lingerie', label: 'Pin-up style polka dot bra and high-waist panties lingerie (复古波点文胸配高腰内裤)' },
  { value: 'Pleated Babydoll Set lingerie', label: 'Pleated Babydoll Set lingerie (褶皱睡裙套装)' },
  { value: 'Plunge Backless Bodysuit lingerie', label: 'Plunge Backless Bodysuit lingerie (深V露背紧身衣)' },
  { value: 'Plush Velvet Robe lingerie', label: 'Plush Velvet Robe lingerie (天鹅绒长袍)' },
  { value: 'Polka Dot Push-Up Bra lingerie', label: 'Polka Dot Push-Up Bra lingerie (波点聚拢文胸)' },
  { value: 'Polka Dot Tanga Brief lingerie', label: 'Polka Dot Tanga Brief lingerie (波点坦加内裤)' },
  { value: 'Printed Microfiber Brief lingerie', label: 'Printed Microfiber Brief lingerie (印花超细纤维内裤)' },
  { value: 'Racerback Sports Bra lingerie', label: 'Racerback Sports Bra lingerie (竞速背运动文胸)' },
  { value: 'Red silk chemise with delicate lace trim lingerie', label: 'Red silk chemise with delicate lace trim lingerie (红色丝绸衬裙配精致蕾丝边)' },
  { value: 'Red velvet corset with a matching mini cape lingerie', label: 'Red velvet corset with a matching mini cape lingerie (红色天鹅绒塑身衣配迷你披肩)' },
  { value: 'Rhinestone Garter Belt lingerie', label: 'Rhinestone Garter Belt lingerie (水钻吊袜带)' },
  { value: 'Rhinestone Studded Teddy lingerie', label: 'Rhinestone Studded Teddy lingerie (水钻铆钉连体衣)' },
  { value: 'Rhinestone Trim Bra lingerie', label: 'Rhinestone Trim Bra lingerie (水钻边饰文胸)' },
  { value: 'Ribbed Cotton Bodysuit lingerie', label: 'Ribbed Cotton Bodysuit lingerie (罗纹棉质紧身衣)' },
  { value: 'Ribbed Seamless Thong lingerie', label: 'Ribbed Seamless Thong lingerie (罗纹无缝丁字裤)' },
  { value: 'Romantic off-shoulder lace boudoir dress lingerie', label: 'Romantic off-shoulder lace boudoir dress lingerie (浪漫露肩蕾丝闺房裙)' },
  { value: 'Ruched Mesh Bodysuit lingerie', label: 'Ruched Mesh Bodysuit lingerie (褶皱网纱紧身衣)' },
  { value: 'Ruffle Edge Teddy lingerie', label: 'Ruffle Edge Teddy lingerie (褶皱边连体衣)' },
  { value: 'Ruffled Cotton Chemise lingerie', label: 'Ruffled Cotton Chemise lingerie (棉质褶皱衬裙)' },
  { value: 'Ruffled Hem Chemise lingerie', label: 'Ruffled Hem Chemise lingerie (褶边衬裙)' },
  { value: 'Ruffled Lace Boyshorts lingerie', label: 'Ruffled Lace Boyshorts lingerie (褶皱蕾丝平角裤)' },
  { value: 'Ruffled Mesh Teddy lingerie', label: 'Ruffled Mesh Teddy lingerie (褶皱网纱连体衣)' },
  { value: 'Satin Bow-Tie Teddy lingerie', label: 'Satin Bow-Tie Teddy lingerie (缎面蝴蝶结连体衣)' },
  { value: 'Satin Chemise with Lace Trim lingerie', label: 'Satin Chemise with Lace Trim lingerie (缎面蕾丝衬裙)' },
  { value: 'Satin Crossover Bralette lingerie', label: 'Satin Crossover Bralette lingerie (缎面交叉文胸)' },
  { value: 'Satin Edge Boyshorts lingerie', label: 'Satin Edge Boyshorts lingerie (缎面平角裤)' },
  { value: 'Satin Embroidered Bralette lingerie', label: 'Satin Embroidered Bralette lingerie (缎面刺绣文胸)' },
  { value: 'Satin Lace-Up Panty lingerie', label: 'Satin Lace-Up Panty lingerie (缎面绑带内裤)' },
  { value: 'Satin Paneled Bralette lingerie', label: 'Satin Paneled Bralette lingerie (缎面嵌件文胸)' },
  { value: 'Satin Peplum Corset lingerie', label: 'Satin Peplum Corset lingerie (缎面腰部装饰塑身衣)' },
  { value: 'Satin Ruched Bustier lingerie', label: 'Satin Ruched Bustier lingerie (缎面褶皱紧身胸衣)' },
  { value: 'Satin Ruffle Bralette lingerie', label: 'Satin Ruffle Bralette lingerie (缎面褶皱文胸)' },
  { value: 'Satin Scoop Bodysuit lingerie', label: 'Satin Scoop Bodysuit lingerie (缎面圆领紧身衣)' },
  { value: 'Satin Trim Lace Bodysuit lingerie', label: 'Satin Trim Lace Bodysuit lingerie (缎面蕾丝紧身衣)' },
  { value: 'Satin and Lace Robe Set lingerie', label: 'Satin and Lace Robe Set lingerie (缎面蕾丝长袍套装)' },
  { value: 'Satin and Lace Slip lingerie', label: 'Satin and Lace Slip lingerie (缎面蕾丝吊带裙)' },
  { value: 'Satin slip nightgown with side slits and lace cups lingerie', label: 'Satin slip nightgown with side slits and lace cups lingerie (侧开衩缎面睡袍配蕾丝杯)' },
  { value: 'Scallop edge lace wraparound bralette and panty lingerie', label: 'Scallop edge lace wraparound bralette and panty lingerie (扇形蕾丝裹身文胸和内裤)' },
  { value: 'Scalloped Lace Bra lingerie', label: 'Scalloped Lace Bra lingerie (扇形蕾丝文胸)' },
  { value: 'Scoop Neck Camisole Bra lingerie', label: 'Scoop Neck Camisole Bra lingerie (圆领吊带背心文胸)' },
  { value: 'Sculpted Push-Up Bra lingerie', label: 'Sculpted Push-Up Bra lingerie (塑形聚拢文胸)' },
  { value: 'Seamless Sport Thong lingerie', label: 'Seamless Sport Thong lingerie (无缝运动丁字裤)' },
  { value: 'Seamless Strappy Thong Bodysuit lingerie', label: 'Seamless Strappy Thong Bodysuit lingerie (无缝绑带丁字裤紧身衣)' },
  { value: 'See-through chiffon full-length nightgown lingerie', label: 'See-through chiffon full-length nightgown lingerie (透视雪纺长睡袍)' },
  { value: 'Sequin Detail Corset lingerie', label: 'Sequin Detail Corset lingerie (亮片细节塑身衣)' },
  { value: 'Sequined Bralette lingerie', label: 'Sequined Bralette lingerie (亮片文胸)' },
  { value: 'Sequined bra top with high-waist lace briefs lingerie', label: 'Sequined bra top with high-waist lace briefs lingerie (亮片罩杯配高腰蕾丝内裤)' },
  { value: 'Sheer Caged Bodysuit lingerie', label: 'Sheer Caged Bodysuit lingerie (透视镂空紧身衣)' },
  { value: 'Sheer Cutout Chemise lingerie', label: 'Sheer Cutout Chemise lingerie (透视镂空衬裙)' },
  { value: 'Sheer Dot Mesh Bodysuit lingerie', label: 'Sheer Dot Mesh Bodysuit lingerie (透视圆点网纱紧身衣)' },
  { value: 'Sheer Embroidered Garter Belt lingerie', label: 'Sheer Embroidered Garter Belt lingerie (透视刺绣吊袜带)' },
  { value: 'Sheer Embroidered Thong lingerie', label: 'Sheer Embroidered Thong lingerie (透视刺绣丁字裤)' },
  { value: 'Sheer Floral Chemise lingerie', label: 'Sheer Floral Chemise lingerie (透视花卉衬裙)' },
  { value: 'Sheer Lace Bustier lingerie', label: 'Sheer Lace Bustier lingerie (透视蕾丝紧身胸衣)' },
  { value: 'Sheer Lace Chemise lingerie', label: 'Sheer Lace Chemise lingerie (透视蕾丝衬裙)' },
  { value: 'Sheer Lace Garter Belt lingerie', label: 'Sheer Lace Garter Belt lingerie (透视蕾丝吊袜带)' },
  { value: 'Sheer Long Sleeve Bodystocking lingerie', label: 'Sheer Long Sleeve Bodystocking lingerie (透视长袖连体袜)' },
  { value: 'Sheer Marabou Babydoll lingerie', label: 'Sheer Marabou Babydoll lingerie (透视羽毛睡裙)' },
  { value: 'Sheer Mesh Garter Belt lingerie', label: 'Sheer Mesh Garter Belt lingerie (透视网纱吊袜带)' },
  { value: 'Sheer Mesh Nightgown lingerie', label: 'Sheer Mesh Nightgown lingerie (透视网纱睡袍)' },
  { value: 'Sheer Panel Bustier lingerie', label: 'Sheer Panel Bustier lingerie (透视嵌件紧身胸衣)' },
  { value: 'Sheer Polka Dot Babydoll lingerie', label: 'Sheer Polka Dot Babydoll lingerie (透视波点睡裙)' },
  { value: 'Sheer Ruffle Corset lingerie', label: 'Sheer Ruffle Corset lingerie (透视褶皱塑身衣)' },
  { value: 'Sheer Slip Dress lingerie', label: 'Sheer Slip Dress lingerie (透视吊带裙)' },
  { value: 'Sheer Tulle Bodysuit lingerie', label: 'Sheer Tulle Bodysuit lingerie (透视薄纱紧身衣)' },
  { value: 'Sheer embroidered cape with matching thong lingerie', label: 'Sheer embroidered cape with matching thong lingerie (透视刺绣披肩配同款丁字裤)' },
  { value: 'Sheer mesh bodysuit with strategically placed embroidery lingerie', label: 'Sheer mesh bodysuit with strategically placed embroidery lingerie (策略性刺绣透视网纱紧身衣)' },
  { value: 'Sheer tulle peignoir with feather trim lingerie', label: 'Sheer tulle peignoir with feather trim lingerie (羽毛边透视薄纱长袍)' },
  { value: 'Silk Balconette Bra lingerie', label: 'Silk Balconette Bra lingerie (丝绸短杯文胸)' },
  { value: 'Silk Blend Control Briefs lingerie', label: 'Silk Blend Control Briefs lingerie (丝绸混纺控制内裤)' },
  { value: 'Silk Kimono Robe lingerie', label: 'Silk Kimono Robe lingerie (丝绸和服长袍)' },
  { value: 'Silk Sleep Chemise lingerie', label: 'Silk Sleep Chemise lingerie (丝绸睡眠衬裙)' },
  { value: 'Silk Tie Bralette lingerie', label: 'Silk Tie Bralette lingerie (丝绸绑带文胸)' },
  { value: 'Silk Wrap Teddy lingerie', label: 'Silk Wrap Teddy lingerie (丝绸裹身连体衣)' },
  { value: 'Silk charmeuse pajama set with piping details lingerie', label: 'Silk charmeuse pajama set with piping details lingerie (丝绸睡衣套装配滚边细节)' },
  { value: 'Soft jersey lounge set with lace insets lingerie', label: 'Soft jersey lounge set with lace insets lingerie (柔软针织家居套装配蕾丝嵌件)' },
  { value: 'Sporty bralette and high-waist shorts in stretch cotton lingerie', label: 'Sporty bralette and high-waist shorts in stretch cotton lingerie (运动文胸配高腰棉质短裤)' },
  { value: 'Strap Detail Thong lingerie', label: 'Strap Detail Thong lingerie (绑带细节丁字裤)' },
  { value: 'Strapless Bustier Set lingerie', label: 'Strapless Bustier Set lingerie (无肩带紧身胸衣套装)' },
  { value: 'Strappy Back Brief lingerie', label: 'Strappy Back Brief lingerie (绑带背内裤)' },
  { value: 'Strappy Halter Bra lingerie', label: 'Strappy Halter Bra lingerie (绑带吊带文胸)' },
  { value: 'Strappy Lace Panties lingerie', label: 'Strappy Lace Panties lingerie (绑带蕾丝内裤)' },
  { value: 'Strappy Lace-Up Teddy lingerie', label: 'Strappy Lace-Up Teddy lingerie (绑带绑带连体衣)' },
  { value: 'Strappy Mesh Bodysuit lingerie', label: 'Strappy Mesh Bodysuit lingerie (绑带网纱紧身衣)' },
  { value: 'Strappy Satin Teddy lingerie', label: 'Strappy Satin Teddy lingerie (绑带缎面连体衣)' },
  { value: 'Strappy black cage bra and matching thong lingerie', label: 'Strappy black cage bra and matching thong lingerie (黑色笼式文胸配同款丁字裤)' },
  { value: 'Stretch Lace Halter Bralette lingerie', label: 'Stretch Lace Halter Bralette lingerie (弹力蕾丝吊带文胸)' },
  { value: 'Stretch Satin Garter Belt lingerie', label: 'Stretch Satin Garter Belt lingerie (弹力缎面吊袜带)' },
  { value: 'Stretch Silk Bralette lingerie', label: 'Stretch Silk Bralette lingerie (弹力丝绸文胸)' },
  { value: 'Stretch Velvet Bodysuit lingerie', label: 'Stretch Velvet Bodysuit lingerie (弹力天鹅绒紧身衣)' },
  { value: 'Stretch lace off-shoulder top with miniskirt lingerie', label: 'Stretch lace off-shoulder top with miniskirt lingerie (弹力蕾丝露肩上衣配超短裙)' },
  { value: 'Striped Mesh Teddy lingerie', label: 'Striped Mesh Teddy lingerie (条纹网纱连体衣)' },
  { value: 'Tie-Back Halter Bra lingerie', label: 'Tie-Back Halter Bra lingerie (绑背吊带文胸)' },
  { value: 'Tulle Peplum Bustier lingerie', label: 'Tulle Peplum Bustier lingerie (薄纱腰部装饰紧身胸衣)' },
  { value: 'Tulle Ruffle Bralette lingerie', label: 'Tulle Ruffle Bralette lingerie (薄纱褶皱文胸)' },
  { value: 'Tulle Skirted Thong lingerie', label: 'Tulle Skirted Thong lingerie (薄纱裙摆丁字裤)' },
  { value: 'Unlined Lace Apron Babydoll Set lingerie', label: 'Unlined Lace Apron Babydoll Set lingerie (无衬蕾丝围裙睡裙套装)' },
  { value: 'Velour Lounge Set lingerie', label: 'Velour Lounge Set lingerie (丝绒家居套装)' },
  { value: 'Velvet Applique Bralette lingerie', label: 'Velvet Applique Bralette lingerie (天鹅绒贴花文胸)' },
  { value: 'Velvet Banded Bra lingerie', label: 'Velvet Banded Bra lingerie (天鹅绒带文胸)' },
  { value: 'Velvet Cut-Out Bodysuit lingerie', label: 'Velvet Cut-Out Bodysuit lingerie (天鹅绒镂空紧身衣)' },
  { value: 'Velvet Fringe Bodysuit lingerie', label: 'Velvet Fringe Bodysuit lingerie (天鹅绒流苏紧身衣)' },
  { value: 'Velvet Halter Bralette lingerie', label: 'Velvet Halter Bralette lingerie (天鹅绒吊带文胸)' },
  { value: 'Velvet High Waist Panty lingerie', label: 'Velvet High Waist Panty lingerie (天鹅绒高腰内裤)' },
  { value: 'Velvet Lace-Up Bustier lingerie', label: 'Velvet Lace-Up Bustier lingerie (天鹅绒绑带紧身胸衣)' },
  { value: 'Velvet Lounge Shorts lingerie', label: 'Velvet Lounge Shorts lingerie (天鹅绒家居短裤)' },
  { value: 'Velvet Paneled Bralette lingerie', label: 'Velvet Paneled Bralette lingerie (天鹅绒嵌件文胸)' },
  { value: 'Velvet Strappy Bra lingerie', label: 'Velvet Strappy Bra lingerie (天鹅绒绑带文胸)' },
  { value: 'Velvet Trim Babydoll lingerie', label: 'Velvet Trim Babydoll lingerie (天鹅绒边饰睡裙)' },
  { value: 'Velvet Trim Corset lingerie', label: 'Velvet Trim Corset lingerie (天鹅绒边饰塑身衣)' },
  { value: 'Velvet and Lace Teddy lingerie', label: 'Velvet and Lace Teddy lingerie (天鹅绒蕾丝连体衣)' },
  { value: 'Vintage-inspired high-waisted briefs and bra set with polka dots lingerie', label: 'Vintage-inspired high-waisted briefs and bra set with polka dots lingerie (复古高腰波点内裤和文胸套装)' },
  { value: 'White satin corset with garter belts and sheer stockings lingerie', label: 'White satin corset with garter belts and sheer stockings lingerie (白色缎面塑身衣配吊袜带和透明长筒袜)' },
  { value: 'Zip Detail Sports Bra lingerie', label: 'Zip Detail Sports Bra lingerie (拉链细节运动文胸)' },
  { value: 'Zip-Front Sports Bra lingerie', label: 'Zip-Front Sports Bra lingerie (前拉链运动文胸)' },
  { value: 'String Thong lingerie', label: 'String Thong lingerie (细线丁字裤)' },
  { value: 'Crotchless Panty lingerie', label: 'Crotchless Panty lingerie (开裆内裤)' },
  { value: 'Crotchless Bodysuit lingerie', label: 'Crotchless Bodysuit lingerie (开裆连体衣)' },
  { value: 'Open Cup Bra lingerie', label: 'Open Cup Bra lingerie (敞口杯文胸)' },
  { value: 'Pasties lingerie', label: 'Pasties lingerie (乳贴)' },
  { value: 'Suspender Belt lingerie', label: 'Suspender Belt lingerie (吊袜带)' },
  { value: 'Garter Belt and Stockings lingerie', label: 'Garter Belt and Stockings lingerie (吊袜带+长筒袜)' },
  { value: 'Sheer Stockings lingerie', label: 'Sheer Stockings lingerie (透明丝袜)' },
  { value: 'Fishnet Stockings lingerie', label: 'Fishnet Stockings lingerie (渔网丝袜)' },
  { value: 'Thigh High Boots', label: 'Thigh High Boots (过膝靴)' },
  { value: 'High Heels', label: 'High Heels (高跟鞋)' },
  { value: 'Latex Gloves', label: 'Latex Gloves (乳胶手套)' },
  { value: 'Latex Stockings', label: 'Latex Stockings (乳胶丝袜)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const PROPS_OPTIONS = [
  { value: 'Handcuffs', label: 'Handcuffs (手铐)' },
  { value: 'Leather Handcuffs', label: 'Leather Handcuffs (皮革手铐)' },
  { value: 'Whip', label: 'Whip (皮鞭)' },
  { value: 'Flogger Whip', label: 'Flogger Whip (皮拍鞭)' },
  { value: 'Riding Crop', label: 'Riding Crop (马鞭)' },
  { value: 'Paddle', label: 'Paddle (拍子)' },
  { value: 'Wartenberg Wheel', label: 'Wartenberg Wheel (刺轮)' },
  { value: 'Cat O Nine Tails', label: 'Cat O Nine Tails (九尾鞭)' },
  { value: 'Leash', label: 'Leash (牵引绳)' },
  { value: 'Collar', label: 'Collar (项圈)' },
  { value: 'Spike Collar', label: 'Spike Collar (尖刺项圈)' },
  { value: 'Shock Collar', label: 'Shock Collar (电击项圈)' },
  { value: 'Rope Bondage', label: 'Rope Bondage (绳艺)' },
  { value: 'Shibari Rope', label: 'Shibari Rope (束缚绳)' },
  { value: 'Suspended Bondage', label: 'Suspended Bondage (悬吊束缚)' },
  { value: 'Metal Chains', label: 'Metal Chains (铁链)' },
  { value: 'Ball Gag', label: 'Ball Gag (口球)' },
  { value: 'Ring Gag', label: 'Ring Gag (开口器)' },
  { value: 'Bit Gag', label: 'Bit Gag (马嚼口球)' },
  { value: 'Feather Toy', label: 'Feather Toy (羽毛玩具)' },
  { value: 'Candle Wax Drip', label: 'Candle Wax Drip (蜡烛滴蜡)' },
  { value: 'Ice Cube', label: 'Ice Cube (冰块)' },
  { value: 'Vibrator', label: 'Vibrator (按摩棒)' },
  { value: 'Dildo', label: 'Dildo (假阳具)' },
  { value: 'Butt Plug', label: 'Butt Plug (后庭塞)' },
  { value: 'Sex Machine', label: 'Sex Machine (伸缩椅)' },
  { value: 'Clamps', label: 'Clamps (夹子)' },
  { value: 'Clothespins', label: 'Clothespins (衣夹)' },
  { value: 'Nipple Clamps', label: 'Nipple Clamps (乳头夹)' },
  { value: 'Barbed Wire', label: 'Barbed Wire (铁丝网)' },
  { value: 'Knife', label: 'Knife (刀)' },
  { value: 'Needles', label: 'Needles (针)' },
  { value: 'Tape', label: 'Tape (胶带束缚)' },
  { value: 'Mask', label: 'Mask (面具)' },
  { value: 'Gag Mask', label: 'Gag Mask (封口面具)' },
  { value: 'Blindfold', label: 'Blindfold (眼罩)' },
  { value: 'Ear Plugs', label: 'Ear Plugs (耳塞)' },
  { value: 'Electro Stim', label: 'Electro Stim (电刺激)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const CAMERA_ANGLE_OPTIONS = [
  { value: 'Overhead Shot', label: 'Overhead Shot (俯拍/顶拍)' },
  { value: 'Top-down Shot', label: 'Top-down Shot (垂直俯拍)' },
  { value: 'High Angle', label: 'High Angle (高角度俯视)' },
  { value: 'Dutch Angle', label: 'Dutch Angle (荷兰角/倾斜镜头)' },
  { value: 'Eye Level Shot', label: 'Eye Level Shot (平视)' },
  { value: 'Straight On Shot', label: 'Straight On Shot (正面直拍)' },
  { value: 'Low Angle', label: 'Low Angle (仰视/蚂蚁视角)' },
  { value: 'Cowboy Shot', label: 'Cowboy Shot (牛仔视角/大腿中段)' },
  { value: 'Crotch Level Shot', label: 'Crotch Level Shot (胯部视角)' },
  { value: 'POV Shot', label: 'POV Shot (第一视角/主观镜头)' },
  { value: 'First Person View', label: 'First Person View (第一人称视角)' },
  { value: 'Close Up Shot', label: 'Close Up Shot (特写)' },
  { value: 'Extreme Close Up', label: 'Extreme Close Up (大特写)' },
  { value: 'Medium Shot', label: 'Medium Shot (中景)' },
  { value: 'Full Body Shot', label: 'Full Body Shot (全身)' },
  { value: 'Long Shot', label: 'Long Shot (远景/全景)' },
  { value: 'Wide Shot', label: 'Wide Shot (广角镜头)' },
  { value: 'Portrait Shot', label: 'Portrait Shot (肖像特写)' },
  { value: 'Three-quarter View', label: 'Three-quarter View (四分之三视角)' },
  { value: 'Profile Shot', label: 'Profile Shot (侧面照)' },
  { value: 'Back View', label: 'Back View (背面照)' },
  { value: 'Ass Shot', label: 'Ass Shot (臀部特写)' },
  { value: 'Upward Angled Close-up', label: 'Upward Angled Close-up (微仰特写)' },
  { value: 'Bird Eye View', label: 'Bird Eye View (鸟瞰)' },
  { value: 'Worm Eye View', label: 'Worm Eye View (虫视/超低仰拍)' },
  { value: 'From Behind Shot', label: 'From Behind Shot (身后跟拍)' },
  { value: 'Doggystyle View', label: 'Doggystyle View (后入视角)' },
  { value: 'Missionary View', label: 'Missionary View (传教士视角)' },
  { value: 'Legs Spread Shot', label: 'Legs Spread Shot (双腿张开)' },
  { value: 'Reflection Shot', label: 'Reflection Shot (镜面反射)' },
  { value: '-', label: '不指定' },
  { value: 'random 🎲', label: '随机' },
];

export const DEFAULT_TXT2IMG_PARAMS = {
  width: 1024,
  height: 1536,
  imageCount: 3,
  enableNegativePrompt: false,
  prompt: '',
  lora1Name: '',
  lora1Weight: 0.8,
  lora2Name: '',
  lora2Weight: 0.6,
  lora3Name: '',
  lora3Weight: 1.0,
  enableRandomPrompt: true,
  checkpoint: '',
  bodyType: '-',
  facialExpression: '-',
  hairColor: '-',
  hairLength: '-',
  hairStyle: '-',
  shot: '-',
  clothes: '-',
  femaleLingerie: '-',
  lightDirection: '-',
  lightType: '-',
  modelPose: '-',
  props: [],
  cameraAngle: '-',
};
